### ISSUE TITLE
Parenthesis in the replay name prevent file merging

### ISSUE THREAD

**Issue by bobtheblueberry** [hcallen/dlive-dl#1]
Windows apparently doesn't like certain characters in file names such as parenthesis. If a replay title has invalid characters the parts will download but will not merge properly, producing an empty file with no extension.

Workaround:
  Change line 105 to:  
      self.filename = f'{self.user}-replay-{resolution}-{quality}.mp4'

**Comment by hcallen** [comment]
Pushed fix to replace title with vod id in filename.
