### ISSUE TITLE
Doesn't work (anymore)?!

### ISSUE THREAD

**Issue by yustAnotherUser** [hcallen/dlive-dl#2]
Hi there,

in the following environment
```
$ uname -r
5.4.0-1047-raspi
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

when I invoke:
`python3 dlive-dl.py -o /downloaddir/ https://dlive.tv/p/hellwach.tv+qUqrv027R`

I get:
```
Traceback (most recent call last):
  File "dlive-dl.py", line 185, in <module>
    main()
  File "dlive-dl.py", line 27, in main
    info = pb_info['defaultClient'][root_query]
KeyError: '$ROOT_QUERY.pastBroadcast({"permlink":"hellwach.tv+qUqrv027R"})'
```

on every replay I tried on every channel.
Any chance for a fix or a advise what to do? I'm a little lost here...
Thanks in advance.

**Comment by hcallen** [comment]
I updated the script to account for the new way dlive sends playback info.

Thanks for letting me know.
